/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AujourdhuiRouteImport } from './routes/aujourdhui'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedRedactionIndexRouteImport } from './routes/_authenticated/redaction.index'
import { Route as AuthenticatedRedactionIdRouteImport } from './routes/_authenticated/redaction.$id'
import { Route as AuthenticatedRedactionCompteRouteImport } from './routes/_authenticated/redaction.compte'
import { Route as AuthenticatedRedactionDirectRouteImport } from './routes/_authenticated/redaction.direct'
import { Route as AuthenticatedRedactionPartagesRouteImport } from './routes/_authenticated/redaction.partages'
import { Route as AuthenticatedRedactionPubliciteRouteImport } from './routes/_authenticated/redaction.publicite'
import { Route as AuthenticatedRedactionReseauxRouteImport } from './routes/_authenticated/redaction.reseaux'
import { Route as AuthenticatedRedactionXRouteImport } from './routes/_authenticated/redaction.x'
import { Route as ApiPublicDirectHealthRouteImport } from './routes/api/public/direct-health'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as ApiPublicRadioStationRouteImport } from './routes/api/public/radio.$station'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AujourdhuiRoute = AujourdhuiRouteImport.update({
  id: '/aujourdhui',
  path: '/aujourdhui',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRedactionIndexRoute =
  AuthenticatedRedactionIndexRouteImport.update({
    id: '/redaction/',
    path: '/redaction/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedactionIdRoute =
  AuthenticatedRedactionIdRouteImport.update({
    id: '/redaction/$id',
    path: '/redaction/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedactionCompteRoute =
  AuthenticatedRedactionCompteRouteImport.update({
    id: '/redaction/compte',
    path: '/redaction/compte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedactionDirectRoute =
  AuthenticatedRedactionDirectRouteImport.update({
    id: '/redaction/direct',
    path: '/redaction/direct',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedactionPartagesRoute =
  AuthenticatedRedactionPartagesRouteImport.update({
    id: '/redaction/partages',
    path: '/redaction/partages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedactionPubliciteRoute =
  AuthenticatedRedactionPubliciteRouteImport.update({
    id: '/redaction/publicite',
    path: '/redaction/publicite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedactionReseauxRoute =
  AuthenticatedRedactionReseauxRouteImport.update({
    id: '/redaction/reseaux',
    path: '/redaction/reseaux',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedactionXRoute = AuthenticatedRedactionXRouteImport.update({
  id: '/redaction/x',
  path: '/redaction/x',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDirectHealthRoute = ApiPublicDirectHealthRouteImport.update({
  id: '/api/public/direct-health',
  path: '/api/public/direct-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRadioStationRoute = ApiPublicRadioStationRouteImport.update({
  id: '/api/public/radio/$station',
  path: '/api/public/radio/$station',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/a-propos': typeof AProposRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/auth': typeof AuthRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/redaction/$id': typeof AuthenticatedRedactionIdRoute
  '/redaction/compte': typeof AuthenticatedRedactionCompteRoute
  '/redaction/direct': typeof AuthenticatedRedactionDirectRoute
  '/redaction/partages': typeof AuthenticatedRedactionPartagesRoute
  '/redaction/publicite': typeof AuthenticatedRedactionPubliciteRoute
  '/redaction/reseaux': typeof AuthenticatedRedactionReseauxRoute
  '/redaction/x': typeof AuthenticatedRedactionXRoute
  '/api/public/direct-health': typeof ApiPublicDirectHealthRoute
  '/redaction/': typeof AuthenticatedRedactionIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/radio/$station': typeof ApiPublicRadioStationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/a-propos': typeof AProposRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/auth': typeof AuthRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/redaction/$id': typeof AuthenticatedRedactionIdRoute
  '/redaction/compte': typeof AuthenticatedRedactionCompteRoute
  '/redaction/direct': typeof AuthenticatedRedactionDirectRoute
  '/redaction/partages': typeof AuthenticatedRedactionPartagesRoute
  '/redaction/publicite': typeof AuthenticatedRedactionPubliciteRoute
  '/redaction/reseaux': typeof AuthenticatedRedactionReseauxRoute
  '/redaction/x': typeof AuthenticatedRedactionXRoute
  '/api/public/direct-health': typeof ApiPublicDirectHealthRoute
  '/redaction': typeof AuthenticatedRedactionIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/radio/$station': typeof ApiPublicRadioStationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/$slug': typeof SlugRoute
  '/a-propos': typeof AProposRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/auth': typeof AuthRoute
  '/recherche': typeof RechercheRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/_authenticated/redaction/$id': typeof AuthenticatedRedactionIdRoute
  '/_authenticated/redaction/compte': typeof AuthenticatedRedactionCompteRoute
  '/_authenticated/redaction/direct': typeof AuthenticatedRedactionDirectRoute
  '/_authenticated/redaction/partages': typeof AuthenticatedRedactionPartagesRoute
  '/_authenticated/redaction/publicite': typeof AuthenticatedRedactionPubliciteRoute
  '/_authenticated/redaction/reseaux': typeof AuthenticatedRedactionReseauxRoute
  '/_authenticated/redaction/x': typeof AuthenticatedRedactionXRoute
  '/api/public/direct-health': typeof ApiPublicDirectHealthRoute
  '/_authenticated/redaction/': typeof AuthenticatedRedactionIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/radio/$station': typeof ApiPublicRadioStationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$slug'
    | '/a-propos'
    | '/aujourdhui'
    | '/auth'
    | '/recherche'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/redaction/$id'
    | '/redaction/compte'
    | '/redaction/direct'
    | '/redaction/partages'
    | '/redaction/publicite'
    | '/redaction/reseaux'
    | '/redaction/x'
    | '/api/public/direct-health'
    | '/redaction/'
    | '/api/public/media/$'
    | '/api/public/radio/$station'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$slug'
    | '/a-propos'
    | '/aujourdhui'
    | '/auth'
    | '/recherche'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/redaction/$id'
    | '/redaction/compte'
    | '/redaction/direct'
    | '/redaction/partages'
    | '/redaction/publicite'
    | '/redaction/reseaux'
    | '/redaction/x'
    | '/api/public/direct-health'
    | '/redaction'
    | '/api/public/media/$'
    | '/api/public/radio/$station'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/$slug'
    | '/a-propos'
    | '/aujourdhui'
    | '/auth'
    | '/recherche'
    | '/robots.txt'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/_authenticated/redaction/$id'
    | '/_authenticated/redaction/compte'
    | '/_authenticated/redaction/direct'
    | '/_authenticated/redaction/partages'
    | '/_authenticated/redaction/publicite'
    | '/_authenticated/redaction/reseaux'
    | '/_authenticated/redaction/x'
    | '/api/public/direct-health'
    | '/_authenticated/redaction/'
    | '/api/public/media/$'
    | '/api/public/radio/$station'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  SlugRoute: typeof SlugRoute
  AProposRoute: typeof AProposRoute
  AujourdhuiRoute: typeof AujourdhuiRoute
  AuthRoute: typeof AuthRoute
  RechercheRoute: typeof RechercheRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ApiPublicDirectHealthRoute: typeof ApiPublicDirectHealthRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicRadioStationRoute: typeof ApiPublicRadioStationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aujourdhui': {
      id: '/aujourdhui'
      path: '/aujourdhui'
      fullPath: '/aujourdhui'
      preLoaderRoute: typeof AujourdhuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/redaction/': {
      id: '/_authenticated/redaction/'
      path: '/redaction'
      fullPath: '/redaction/'
      preLoaderRoute: typeof AuthenticatedRedactionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redaction/$id': {
      id: '/_authenticated/redaction/$id'
      path: '/redaction/$id'
      fullPath: '/redaction/$id'
      preLoaderRoute: typeof AuthenticatedRedactionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redaction/compte': {
      id: '/_authenticated/redaction/compte'
      path: '/redaction/compte'
      fullPath: '/redaction/compte'
      preLoaderRoute: typeof AuthenticatedRedactionCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redaction/direct': {
      id: '/_authenticated/redaction/direct'
      path: '/redaction/direct'
      fullPath: '/redaction/direct'
      preLoaderRoute: typeof AuthenticatedRedactionDirectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redaction/partages': {
      id: '/_authenticated/redaction/partages'
      path: '/redaction/partages'
      fullPath: '/redaction/partages'
      preLoaderRoute: typeof AuthenticatedRedactionPartagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redaction/publicite': {
      id: '/_authenticated/redaction/publicite'
      path: '/redaction/publicite'
      fullPath: '/redaction/publicite'
      preLoaderRoute: typeof AuthenticatedRedactionPubliciteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redaction/reseaux': {
      id: '/_authenticated/redaction/reseaux'
      path: '/redaction/reseaux'
      fullPath: '/redaction/reseaux'
      preLoaderRoute: typeof AuthenticatedRedactionReseauxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redaction/x': {
      id: '/_authenticated/redaction/x'
      path: '/redaction/x'
      fullPath: '/redaction/x'
      preLoaderRoute: typeof AuthenticatedRedactionXRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/direct-health': {
      id: '/api/public/direct-health'
      path: '/api/public/direct-health'
      fullPath: '/api/public/direct-health'
      preLoaderRoute: typeof ApiPublicDirectHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radio/$station': {
      id: '/api/public/radio/$station'
      path: '/api/public/radio/$station'
      fullPath: '/api/public/radio/$station'
      preLoaderRoute: typeof ApiPublicRadioStationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRedactionIdRoute: typeof AuthenticatedRedactionIdRoute
  AuthenticatedRedactionCompteRoute: typeof AuthenticatedRedactionCompteRoute
  AuthenticatedRedactionDirectRoute: typeof AuthenticatedRedactionDirectRoute
  AuthenticatedRedactionPartagesRoute: typeof AuthenticatedRedactionPartagesRoute
  AuthenticatedRedactionPubliciteRoute: typeof AuthenticatedRedactionPubliciteRoute
  AuthenticatedRedactionReseauxRoute: typeof AuthenticatedRedactionReseauxRoute
  AuthenticatedRedactionXRoute: typeof AuthenticatedRedactionXRoute
  AuthenticatedRedactionIndexRoute: typeof AuthenticatedRedactionIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRedactionIdRoute: AuthenticatedRedactionIdRoute,
  AuthenticatedRedactionCompteRoute: AuthenticatedRedactionCompteRoute,
  AuthenticatedRedactionDirectRoute: AuthenticatedRedactionDirectRoute,
  AuthenticatedRedactionPartagesRoute: AuthenticatedRedactionPartagesRoute,
  AuthenticatedRedactionPubliciteRoute: AuthenticatedRedactionPubliciteRoute,
  AuthenticatedRedactionReseauxRoute: AuthenticatedRedactionReseauxRoute,
  AuthenticatedRedactionXRoute: AuthenticatedRedactionXRoute,
  AuthenticatedRedactionIndexRoute: AuthenticatedRedactionIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  SlugRoute: SlugRoute,
  AProposRoute: AProposRoute,
  AujourdhuiRoute: AujourdhuiRoute,
  AuthRoute: AuthRoute,
  RechercheRoute: RechercheRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategorySlugRoute: CategorySlugRoute,
  ApiPublicDirectHealthRoute: ApiPublicDirectHealthRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicRadioStationRoute: ApiPublicRadioStationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
